trigger: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: CheckTerraform
    displayName: "Check Terraform configuration"

    steps:
      - checkout: self
        clean: true

      - task: Bash@3
        inputs:
          filePath: ./scripts/check-terraform.sh
          workingDirectory: $(System.DefaultWorkingDirectory)
          failOnStderr: true
